const TEAMS = [
  { teamname: 'Arsenal', teamcode: 'ARS' },
  { teamname: 'Aston Villa', teamcode: 'AVL' },
  { teamname: 'Brighton and Hove Albion', teamcode: 'BRI' },
  { teamname: 'Burnley', teamcode: 'BUR' },
  { teamname: 'Chelsea', teamcode: 'CHE' },
  { teamname: 'Crystal Palace', teamcode: 'CRY' },
  { teamname: 'Everton', teamcode: 'EVE' },
  { teamname: 'Fulham', teamcode: 'FUL' },
  { teamname: 'Leeds United', teamcode: 'LEE' },
  { teamname: 'Leicester City', teamcode: 'LEI' },
  { teamname: 'Liverpool', teamcode: 'LIV' },
  { teamname: 'Manchester City', teamcode: 'MCI' },
  { teamname: 'Manchester United', teamcode: 'MUN' },
  { teamname: 'Newcastle United', teamcode: 'NEW' },
  { teamname: 'Southampton', teamcode: 'SOU' },
  { teamname: 'Sheffield United', teamcode: 'SHU' },
  { teamname: 'Tottenham Hotspur', teamcode: 'TOT' },
  { teamname: 'West Bromwich Albion', teamcode: 'WBA' },
  { teamname: 'West Ham United', teamcode: 'WHU' },
  { teamname: 'Wolverhampton Wanderers', teamcode: 'WOL' },
];

const TEAMCODES = [
  'ARS',
  'AVL',
  'BRI',
  'BUR',
  'CHE',
  'CRY',
  'EVE',
  'FUL',
  'LEE',
  'LEI',
  'LIV',
  'MCI',
  'MUN',
  'NEW',
  'SOU',
  'SHU',
  'TOT',
  'WBA',
  'WHU',
  'WOL',
];

module.exports = { TEAMS, TEAMCODES };
